import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import CornerLogo from "./components/CornerLogo";
import CornerLogoLeft from "./components/CornerLogoLeft";

const montserrat = Montserrat({
  subsets: ["latin"],
  variable: "--font-montserrat",
});

export const metadata: Metadata = {
  title: "Sentiment AI",
  description: "Generated by Sentiment AI",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${montserrat.variable} font-sans antialiased`}>
        {children}
        <CornerLogo />
        <CornerLogoLeft />
      </body>
    </html>
  );
}
