import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import CornerLogo from "./components/CornerLogo";
import CornerLogoLeft from "./components/CornerLogoLeft";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "SentimentAI",
  description: "Generated by SentimentAI",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} font-sans antialiased`}>
        {children}
        <CornerLogo />
        <CornerLogoLeft />
      </body>
    </html>
  );
}
